### ISSUE TITLE
Installing via Extension manager fails

### ISSUE THREAD

**Issue by derghostface** [markussom/sitemap_generator#1]
Installing the extension via extension manager (t3x upload) fails with a PHP Warning:
	
PHP Warning: trim() expects parameter 1 to be string, object given in typo3/sysext/core/Classes/Utility/ExtensionManagementUtility.php line 294

PHP 5.6.9
TYPO3 7.6.2

**Comment by markussom** [comment]
Which extensions you have installed before?

**Comment by derghostface** [comment]
It worked with version 0.0.5.

**Comment by markussom** [comment]
Perfect :)
