### ISSUE TITLE
Additional fields as simple text

### ISSUE THREAD

**Issue by r4fx** [markussom/sitemap_generator#18]
Thanks for this great extension, it works pretty.

One thing is missing for most cases, I think,
why not add a possibility to define additional fields not as db field but as plain text ?
In current situation we need to extend each db table of each installed extension to get for example changefreq, 
why not simplify that by allow to set additional fields as simple text, for example:

```
news {
    changefreq = daily
    priority = 0.7
}
```

Please take into consideration to add option like that.

**Comment by markussom** [comment]
Hey,
Thx for the flowsers :)

That is easy. You can fill each field with the TYPO3 Syntax.
z.b. 
`news {
  changefreq = TEXT
  changefreq.value = daily
}`

**Comment by r4fx** [comment]
Brilliant!
This is missing in the user manual.
