### ISSUE TITLE
Add shortcut pages and subpages to sitemap?

### ISSUE THREAD

**Issue by STWcamila** [markussom/sitemap_generator#24]
Not sure if this is the best place for this but I have a question.

I have version 0.8.1 in a typo3 7.6.11 site, if the page is a shortcode, it doesn't get added to the sitemap, nor do any of the subpages.

Is there a way around this?

Great extension btw! Works great with tx_news.

**Comment by markussom** [comment]
Hey :)
you can set in the new version 0.9.x the allowedDoktypes via TypoScript.

in your case set 
`plugin.tx_sitemapgenerator.urlEntries.pages.allowedDoktypes = 1,4`
