### ISSUE TITLE
News not exported in the sitemaps

### ISSUE THREAD

**Issue by gebeleisis** [markussom/sitemap_generator#33]
Hi, i can't manage to get the news articles to be exported in the sitemaps. I only get the few pages i created for the website, but not the news articles that populate these pages. I added the following typoscript in the constants section of my main template (and also included the static template of the extension):

```
plugin.tx_sitemapgenerator {
    urlEntries {
        pages = 1
        pages {
            rootPageId = 1
            allowedDoktypes = 1
            additionalWhere = doktype!=6
        }
    }
}
plugin.tx_sitemapgenerator {
    urlEntries {
        news = 1
        news {
            active = 1
            table = tx_news_domain_model_news
            additionalWhere = pid=6
            orderBy = title DESC
            limit = 0,10
            lastmod = tstamp
            url = TEXT
            url {
                typolink.parameter = 9
                typolink.additionalParams = &tx_news_pi1[controller]=News&tx_news_pi1[action]=detail&tx_news_pi1[news]={field:uid}
                typolink.additionalParams.insertData = 1
                typolink.useCacheHash = 1
                typolink.returnLast = url
                typolink.forceAbsoluteUrl = 1
            }
        }
    }
}
plugin.tx_sitemapgenerator.googleNewsUrlEntry = 1
```

Can you please tell me if this is correct?

**Comment by peterkraume** [comment]
You can remove `limit = 0,10` since you probably want to have all news in your sitemap.

Did you make sure that the `additionalWhere` statement is correct? Is this the sysfolder where the news records are stored?

And please check if `typolink.parameter` has the correct id of the page where the news plugin with the single view is.

**Comment by gebeleisis** [comment]
I removed the limit, i checked the typolink.parameter, the pid is the sysfolder where the news records are stored. however it seems that the query is not properly executed. Is there maybe a select statement missing?

**Comment by peterkraume** [comment]
The select statement is done automatically.
Please check your TypoScript Object Browser, if your above posted code shows up correct there.
For testing purposes you can remove the `additionalWhere` and `orderBy` clauses as well.
Did you check the TYPO3 log for possible SQL errors?

**Comment by gebeleisis** [comment]
The funny thing is that if i remove the typo script code from the template constants, i get the same result, so it seems that that code is somehow ignored

**Comment by gebeleisis** [comment]
dummy mistake. I put the code in constants instead of setup
