### ISSUE TITLE
News seems not to work

### ISSUE THREAD

**Issue by einpraegsam** [markussom/sitemap_generator#35]
Trying to see some news will result in
`Fluid parse error in template Sitemap_action_googleNewsList_35fce49a775b7f9eab7ff40682dc5b9317260cde, line 1 at character 1. Error: Unkown Namespace: &lt;news:news&gt; (error code 0). Template source chunk: `

News version 6.0.0

**Comment by markussom** [comment]
Omg 2h searching ^^ 1 line to resolve

**Comment by einpraegsam** [comment]
Yes, a bit strange to have a pure news-namespace
